# -*- coding: utf-8 -*-
"""molecule viewer WIP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kalFIHHm8T3yBZXFXAROnfE3ditNpizr
"""

# -*- coding: utf-8 -*-
"""
Chem3D-Viewer
Developed by Ali Chaudhary (Greenshaw)
Simple formula visualiser using RDKit and py3dMol
License: MIT
"""


#ali
#put the formula in a 'SMILE' form
#Single bonds are assumed like 'CO'
# use = for double bonds or # for triple bonds
import streamlit as st
from rdkit import Chem
from rdkit.Chem import AllChem
import py3Dmol
from stmol import showmol

#standard imports

def model_3d(smiles):
  mol = Chem.MolFromSmiles(smiles)
  #creates the molecule
  mol = Chem.AddHs(mol)
  #adds hydrogen because for some reason its normally ignored

  AllChem.EmbedMolecule(mol, AllChem.ETKDG())
  #calculates 3d positions based on lengths
  #takes the molecule text and makes it into a mol object python can read
  AllChem.MMFFOptimizeMolecule(mol)
  #optimises by finding a stable version of the molecule


  mblock = Chem.MolToMolBlock(mol)
  view = py3Dmol.view(width=400, height=400)
  view.addModel(mblock, 'mol')
  #makes a 3d viewer

  view.setStyle({'stick': {}, 'sphere': {'scale': 0.3}})
  view.zoomTo()
  return showmol(view, height=400, width=400)
  #edit to now use showmol instead of view()
  #closest thing to the simple ball and stick model


#this is a basic menu and the only user interface
def menu():
  st.title("molecule viewing simulator")
  st.write("remember how to format the SMILE mol")
  st.info("single bonds are assumed, double are = and triple are #")
  st.info("examples are CO or O=C=O")
  print("")
  print("")
  print("press 1 to start or 0 to exit")
  # replaced while loop with gui button
  if st.button("Start Viewer"):

    mol_input = st.text_input("Enter mol string:", "CCO")

    if mol_input:
        try:
            model_3d(mol_input)
        except:
            st.error("Invalid mol string format")


menu()

