# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6cQc3QjkQ0EBv8_s_PZVitHSUrJ5hng
"""

import streamlit as st

st.set_page_config(page_title="Greenshaw Chem Toolkit", layout="wide")

st.title("Ali's Chem Toolkit")
st.write("Select a tool from the sidebar to get started.")

st.info("This toolkit was designed to assist with Chemistry revision and visualization.")


#button shortcuts
st.subheader("Available Tools")
st.subheader("Ideas for future features should be told to me -Ali")
st.markdown("""
- **3D Visualizer:** View any molecule in 3D using SMILES.
- **Molar%ByMass** Calculator
- **Concentration converter** mol/dm3 to g/dm3
- **Interactive Periodic Table**
""")
