# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6cQc3QjkQ0EBv8_s_PZVitHSUrJ5hng
"""
import streamlit as st

def inject_custom_css():
    st.markdown("""
    <style>
        /* Main background and font */
        .stApp {
            background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
            color: #ffffff;
        }
        
        /* Modernized Metric Cards */
        [data-testid="stMetricValue"] {
            font-size: 2.5rem !important;
            font-weight: 700 !important;
            color: #00d4ff !important;
            text-shadow: 0 0 10px rgba(0, 212, 255, 0.5);
        }
        
        /* Glassmorphism containers */
        div[data-testid="stVerticalBlock"] > div:has(div[data-testid="stMetric"]) {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-radius: 15px;
            padding: 20px;
            border: 1px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
        }

        /* Customize the Sidebar */
        section[data-testid="stSidebar"] {
            background-color: rgba(15, 12, 41, 0.8) !important;
        }

        /* Buttons and Inputs */
        .stButton>button {
            border-radius: 20px;
            background: linear-gradient(90deg, #00d4ff, #0080ff);
            color: white;
            border: none;
            transition: 0.3s;
        }
        .stButton>button:hover {
            transform: scale(1.05);
            box-shadow: 0 0 20px rgba(0, 212, 255, 0.6);
        }
    </style>
    """, unsafe_allow_html=True)

# Call the function at the start of your app
inject_custom_css()
import streamlit as st

st.set_page_config(page_title="Greenshaw Chem Toolkit", layout="wide")

st.title("Ali's Chem Toolkit")
st.write("Select a tool from the sidebar to get started.")

st.info("This toolkit was designed to assist with Chemistry revision and visualization.")


#button shortcuts
st.subheader("Available Tools")
st.subheader("Ideas for future features should be told to me -Ali")
st.markdown("""
- **3D Visualizer:** View any molecule in 3D using SMILES.
- **Molar%ByMass** Calculator
- **Concentration converter** mol/dm3 to g/dm3
- **Interactive Periodic Table**
""")
